"""
Lightweight EHR-KnowGen Model
=============================

CPU-friendly demonstration model for the EHR-KnowGen pipeline.

Expected input:
    input_ids:
        Tensor of shape [batch_size, sequence_length]

    attention_mask:
        Tensor of shape [batch_size, sequence_length]

    knowledge_ids:
        Optional tensor of shape [batch_size, knowledge_length]

    knowledge_mask:
        Optional tensor of shape [batch_size, knowledge_length]

Output:
    logits:
        Tensor of shape [batch_size, num_labels]

The model implements a lightweight approximation of the EHR-KnowGen
architecture:

    EHR Input
       |
       v
    Token Embedding
       |
       v
    Transformer Encoder
       |
       +-------------------+
       |                   |
       v                   v
    EHR Representation   Knowledge Representation
       |                   |
       +---------+---------+
                 |
                 v
          Multimodal Fusion
                 |
                 v
            Classification
                 |
                 v
              Logits


Important:
    This is a lightweight demo implementation.
    It is NOT an exact reproduction of the original EHR-KnowGen research model.
"""

from typing import Optional

import torch
import torch.nn as nn


class LightweightEHRKnowGen(nn.Module):
    """
    Lightweight EHR-KnowGen model.

    The model is designed to work with the dataset generated by:

        scripts/02_build_dataset.py

    Main safety fix:
        All input token IDs are validated before they are passed
        to nn.Embedding.

    Invalid IDs are replaced with UNK_ID.

    This prevents:

        IndexError: index out of range in self
    """

    def __init__(
        self,
        vocab_size: int,
        num_labels: int,
        hidden_dim: int = 128,
        num_heads: int = 4,
        num_layers: int = 2,
        dropout: float = 0.1,
        max_seq_len: int = 512,
        pad_id: int = 0,
        unk_id: int = 1,
    ):
        super().__init__()

        # ---------------------------------------------------------
        # Validate configuration
        # ---------------------------------------------------------

        if vocab_size <= 0:
            raise ValueError(
                f"vocab_size must be > 0, got {vocab_size}"
            )

        if num_labels <= 0:
            raise ValueError(
                f"num_labels must be > 0, got {num_labels}"
            )

        if hidden_dim <= 0:
            raise ValueError(
                f"hidden_dim must be > 0, got {hidden_dim}"
            )

        if num_heads <= 0:
            raise ValueError(
                f"num_heads must be > 0, got {num_heads}"
            )

        if hidden_dim % num_heads != 0:
            raise ValueError(
                f"hidden_dim ({hidden_dim}) must be divisible "
                f"by num_heads ({num_heads})"
            )

        # ---------------------------------------------------------
        # Store configuration
        # ---------------------------------------------------------

        self.vocab_size = int(vocab_size)
        self.num_labels = int(num_labels)
        self.hidden_dim = int(hidden_dim)
        self.max_seq_len = int(max_seq_len)

        # Make sure special token IDs are valid.
        self.pad_id = (
            int(pad_id)
            if 0 <= int(pad_id) < self.vocab_size
            else 0
        )

        self.unk_id = (
            int(unk_id)
            if 0 <= int(unk_id) < self.vocab_size
            else self.pad_id
        )

        # ---------------------------------------------------------
        # Token embedding
        # ---------------------------------------------------------

        self.token_embedding = nn.Embedding(
            num_embeddings=self.vocab_size,
            embedding_dim=self.hidden_dim,
            padding_idx=self.pad_id,
        )

        # ---------------------------------------------------------
        # Positional embedding
        # ---------------------------------------------------------

        self.position_embedding = nn.Embedding(
            num_embeddings=self.max_seq_len,
            embedding_dim=self.hidden_dim,
        )

        # ---------------------------------------------------------
        # Transformer encoder
        # ---------------------------------------------------------

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=self.hidden_dim,
            nhead=num_heads,
            dim_feedforward=self.hidden_dim * 4,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )

        self.encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers,
        )

        # ---------------------------------------------------------
        # Layer normalization
        # ---------------------------------------------------------

        self.layer_norm = nn.LayerNorm(
            self.hidden_dim
        )

        # ---------------------------------------------------------
        # Knowledge projection
        #
        # Knowledge tokens are represented using the same
        # vocabulary embedding and projected into the same
        # hidden space.
        # ---------------------------------------------------------

        self.knowledge_projection = nn.Sequential(

            nn.Linear(
                self.hidden_dim,
                self.hidden_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

        )

        # ---------------------------------------------------------
        # Multimodal fusion
        #
        # Combines:
        #
        #   EHR representation
        #   Knowledge representation
        #
        # into a single representation.
        # ---------------------------------------------------------

        self.fusion = nn.Sequential(

            nn.Linear(
                self.hidden_dim * 2,
                self.hidden_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.LayerNorm(
                self.hidden_dim
            ),

        )

        # ---------------------------------------------------------
        # Classification head
        # ---------------------------------------------------------

        self.classifier = nn.Sequential(

            nn.Linear(
                self.hidden_dim,
                self.hidden_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                self.hidden_dim,
                self.num_labels
            ),

        )

    # =============================================================
    # Token ID validation
    # =============================================================

    def _sanitize_token_ids(
        self,
        input_ids: torch.Tensor,
    ) -> torch.Tensor:
        """
        Ensure every token ID is valid for nn.Embedding.

        Valid range:

            0 <= token_id < vocab_size

        Any invalid ID is replaced by UNK_ID.

        This directly prevents:

            IndexError: index out of range in self
        """

        if not torch.is_tensor(input_ids):
            raise TypeError(
                "input_ids must be a torch.Tensor"
            )

        # Convert to integer type.
        input_ids = input_ids.long()

        # Find invalid IDs.
        invalid_mask = (

            (input_ids < 0)

            |

            (input_ids >= self.vocab_size)

        )

        # Replace invalid IDs with UNK.
        if invalid_mask.any():

            input_ids = input_ids.clone()

            input_ids[
                invalid_mask
            ] = self.unk_id

        return input_ids

    # =============================================================
    # Attention mask validation
    # =============================================================

    def _create_attention_mask(
        self,
        input_ids: torch.Tensor,
        attention_mask: Optional[torch.Tensor],
    ) -> torch.Tensor:
        """
        Create a valid boolean attention mask.

        True  = valid token
        False = padding
        """

        if attention_mask is None:

            return (
                input_ids != self.pad_id
            )

        attention_mask = (
            attention_mask
            .to(
                device=input_ids.device
            )
        )

        # Convert to boolean.
        if attention_mask.dtype != torch.bool:

            attention_mask = (
                attention_mask != 0
            )

        return attention_mask

    # =============================================================
    # Position IDs
    # =============================================================

    def _create_position_ids(
        self,
        batch_size: int,
        seq_len: int,
        device: torch.device,
    ) -> torch.Tensor:
        """
        Create positional IDs.

        Example:

            seq_len = 5

            [0, 1, 2, 3, 4]
        """

        positions = torch.arange(

            seq_len,

            device=device,

            dtype=torch.long,

        )

        # If sequence exceeds maximum supported length,
        # wrap positions safely.
        positions = (

            positions
            % self.max_seq_len

        )

        positions = (

            positions
            .unsqueeze(0)
            .expand(
                batch_size,
                -1
            )

        )

        return positions

    # =============================================================
    # Masked mean pooling
    # =============================================================

    def _masked_mean_pooling(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
    ) -> torch.Tensor:
        """
        Mean-pool only valid tokens.

        hidden_states:
            [B, S, H]

        attention_mask:
            [B, S]

        output:
            [B, H]
        """

        mask = (
            attention_mask
            .unsqueeze(-1)
            .float()
        )

        masked_states = (
            hidden_states
            * mask
        )

        token_count = (
            mask.sum(
                dim=1
            )
            .clamp(
                min=1.0
            )
        )

        pooled = (

            masked_states.sum(
                dim=1
            )

            / token_count

        )

        return pooled

    # =============================================================
    # Encode EHR input
    # =============================================================

    def encode_ehr(
        self,
        input_ids: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Encode EHR token sequence.

        Returns:

            [batch_size, hidden_dim]
        """

        # ---------------------------------------------------------
        # Validate token IDs
        # ---------------------------------------------------------

        input_ids = (
            self._sanitize_token_ids(
                input_ids
            )
        )

        batch_size, seq_len = (
            input_ids.shape
        )

        # ---------------------------------------------------------
        # Limit sequence length
        # ---------------------------------------------------------

        if seq_len > self.max_seq_len:

            input_ids = (
                input_ids[
                    :,
                    :self.max_seq_len
                ]
            )

            seq_len = (
                self.max_seq_len
            )

            if attention_mask is not None:

                attention_mask = (
                    attention_mask[
                        :,
                        :self.max_seq_len
                    ]
                )

        # ---------------------------------------------------------
        # Create attention mask
        # ---------------------------------------------------------

        attention_mask = (
            self._create_attention_mask(
                input_ids,
                attention_mask,
            )
        )

        # ---------------------------------------------------------
        # Token embedding
        # ---------------------------------------------------------

        token_embeddings = (
            self.token_embedding(
                input_ids
            )
        )

        # ---------------------------------------------------------
        # Position embedding
        # ---------------------------------------------------------

        position_ids = (
            self._create_position_ids(
                batch_size,
                seq_len,
                input_ids.device,
            )
        )

        position_embeddings = (
            self.position_embedding(
                position_ids
            )
        )

        # ---------------------------------------------------------
        # Combine token + position embeddings
        # ---------------------------------------------------------

        x = (

            token_embeddings

            +

            position_embeddings

        )

        # ---------------------------------------------------------
        # Transformer encoder
        #
        # src_key_padding_mask:
        #
        # True  = ignore token
        # False = process token
        # ---------------------------------------------------------

        padding_mask = (
            ~attention_mask
        )

        x = self.encoder(

            x,

            src_key_padding_mask=
                padding_mask,

        )

        x = (
            self.layer_norm(
                x
            )
        )

        # ---------------------------------------------------------
        # Masked pooling
        # ---------------------------------------------------------

        pooled = (
            self._masked_mean_pooling(
                x,
                attention_mask,
            )
        )

        return pooled

    # =============================================================
    # Encode knowledge
    # =============================================================

    def encode_knowledge(
        self,
        knowledge_ids: Optional[torch.Tensor],
        knowledge_mask: Optional[torch.Tensor] = None,
    ) -> Optional[torch.Tensor]:
        """
        Encode CCS / medical knowledge tokens.

        Returns:

            [batch_size, hidden_dim]

        or None if no knowledge is supplied.
        """

        if knowledge_ids is None:

            return None

        # ---------------------------------------------------------
        # Sanitize knowledge IDs
        # ---------------------------------------------------------

        knowledge_ids = (
            self._sanitize_token_ids(
                knowledge_ids
            )
        )

        batch_size, seq_len = (
            knowledge_ids.shape
        )

        # ---------------------------------------------------------
        # Limit length
        # ---------------------------------------------------------

        if seq_len > self.max_seq_len:

            knowledge_ids = (

                knowledge_ids[
                    :,
                    :self.max_seq_len
                ]

            )

            seq_len = (
                self.max_seq_len
            )

            if knowledge_mask is not None:

                knowledge_mask = (

                    knowledge_mask[
                        :,
                        :self.max_seq_len
                    ]

                )

        # ---------------------------------------------------------
        # Create mask
        # ---------------------------------------------------------

        knowledge_mask = (
            self._create_attention_mask(
                knowledge_ids,
                knowledge_mask,
            )
        )

        # ---------------------------------------------------------
        # Embed knowledge tokens
        # ---------------------------------------------------------

        knowledge_embeddings = (

            self.token_embedding(
                knowledge_ids
            )

        )

        # ---------------------------------------------------------
        # Pool knowledge
        # ---------------------------------------------------------

        knowledge_representation = (

            self._masked_mean_pooling(

                knowledge_embeddings,

                knowledge_mask,

            )

        )

        # ---------------------------------------------------------
        # Project knowledge
        # ---------------------------------------------------------

        knowledge_representation = (

            self.knowledge_projection(

                knowledge_representation

            )

        )

        return knowledge_representation

    # =============================================================
    # Forward pass
    # =============================================================

    def forward(
        self,
        input_ids,
        attention_mask=None,
        knowledge_ids=None,
        knowledge_mask=None,
        css_ids=None,
        css_mask=None,
        labels=None,
    ):
         
        """
        Forward pass.

        Parameters
        ----------
        input_ids:
            EHR token IDs.

        attention_mask:
            EHR attention mask.

        knowledge_ids:
            Optional CCS / medical knowledge token IDs.

        knowledge_mask:
            Optional knowledge attention mask.

        labels:
            Optional target labels.

        Returns
        -------
        dict containing:

            logits
            loss
            ehr_representation
            knowledge_representation
            fused_representation
        """

        # ---------------------------------------------------------
        # Validate input shape
        # ---------------------------------------------------------

        if input_ids.dim() != 2:

            raise ValueError(

                "input_ids must have shape "

                "[batch_size, sequence_length]. "

                f"Received shape: "
                f"{tuple(input_ids.shape)}"

            )

        # ---------------------------------------------------------
        # Encode EHR
        # ---------------------------------------------------------

        ehr_representation = (

            self.encode_ehr(

                input_ids,

                attention_mask,

            )

        )

        # ---------------------------------------------------------
        # Encode knowledge
        # ---------------------------------------------------------

        knowledge_representation = (

            self.encode_knowledge(

                knowledge_ids,

                knowledge_mask,

            )

        )

        # ---------------------------------------------------------
        # If no knowledge is provided,
        # use zero representation.
        # ---------------------------------------------------------

        if knowledge_representation is None:

            knowledge_representation = (

                torch.zeros_like(

                    ehr_representation

                )

            )

        # ---------------------------------------------------------
        # Multimodal fusion
        # ---------------------------------------------------------

        combined = torch.cat(

            [

                ehr_representation,

                knowledge_representation,

            ],

            dim=-1,

        )

        fused_representation = (

            self.fusion(

                combined

            )

        )

        # ---------------------------------------------------------
        # Classification
        # ---------------------------------------------------------

        logits = (

            self.classifier(

                fused_representation

            )

        )

        # ---------------------------------------------------------
        # Calculate loss
        # ---------------------------------------------------------

        loss = None

        if labels is not None:

            # Convert labels to correct type.
            labels = (
                labels.long()
            )

            # Handle [B, 1] labels.
            if labels.dim() > 1:

                labels = (
                    labels.view(-1)
                )

            # Validate label range.
            invalid_labels = (

                (labels < 0)

                |

                (labels >= self.num_labels)

            )

            if invalid_labels.any():

                raise ValueError(

                    "Invalid target label detected. "

                    f"Valid label range is "
                    f"[0, {self.num_labels - 1}], "

                    f"but received labels: "
                    f"{labels.tolist()}"

                )

            loss_fn = (
                nn.CrossEntropyLoss()
            )

            loss = loss_fn(

                logits,

                labels,

            )

        # ---------------------------------------------------------
        # Return output dictionary
        # ---------------------------------------------------------

        return {

            "logits":
                logits,

            "loss":
                loss,

            "ehr_representation":
                ehr_representation,

            "knowledge_representation":
                knowledge_representation,

            "fused_representation":
                fused_representation,

        }


# ================================================================
# Factory helper
# ================================================================

def create_lightweight_model(
    vocab_size: int,
    num_labels: int,
    hidden_dim: int = 128,
    num_heads: int = 4,
    num_layers: int = 2,
    dropout: float = 0.1,
    max_seq_len: int = 512,
    pad_id: int = 0,
    unk_id: int = 1,
):
    """
    Convenience function for creating the model.

    Example:

        model = create_lightweight_model(
            vocab_size=680,
            num_labels=5,
        )
    """

    model = LightweightEHRKnowGen(

        vocab_size=vocab_size,

        num_labels=num_labels,

        hidden_dim=hidden_dim,

        num_heads=num_heads,

        num_layers=num_layers,

        dropout=dropout,

        max_seq_len=max_seq_len,

        pad_id=pad_id,

        unk_id=unk_id,

    )

    return model